language: python

python:
- '3.6'

services:
- postgresql

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -r test-requirements.txt

before_script:
- psql -c 'create database mercury;' -U postgres
- python manage.py migrate
- python manage.py collectstatic --noinput

script:
- black --check --exclude "migrations/" mysite mercury ag_data
- flake8 mysite/ mercury/ ag_data/
- coverage run --source=mysite,mercury,ag_data --omit="migrations/*" manage.py test

after_script:
- coveralls

notifications:
    slack: gcivil-nyu:ahgpmz0a0XgrrUU3E9kPk9kZ

