# Generated by Django 2.2.9 on 2020-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0006_delete_simulateddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindSpeedSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('windSpeed', models.FloatField(default=0)),
            ],
        ),
    ]
